# Generated by Django 5.0.6 on 2024-05-17 15:03

import social_network.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_network", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=social_network.models.post_image_file_path,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=social_network.models.user_image_file_path,
            ),
        ),
    ]
