# Generated by Django 5.0.6 on 2024-05-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_network", "0003_hashtag_post_hashtags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
